# Generated by Django 3.0.2 on 2020-10-02 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extractNews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='sourceId',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
