# Generated by Django 3.0.2 on 2020-10-02 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extractNews', '0003_auto_20201002_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='author',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
