# Generated by Django 3.0.2 on 2020-10-02 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extractNews', '0004_auto_20201002_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='urlToImage',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
